# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build cluster and it's resources
  jobs:
  - job: GenerateOpenshiftConfigurationFiles
    displayName: Generate openshif config file for ARO UPI deployment
    steps:

    # Create directory
    # copy file
    # extract file
    - task: PowerShell@2
      displayName: MakeDirectories
      inputs:
        targetType: 'inline'
        script: |
          mkdir $HOME/var
          mkdir $HOME/clusterconfig
          ls -a

    - task: CopyFiles@2
      inputs:
        sourceFolder:  $(Build.SourcesDirectory)/var
        contents: '**' 
        targetFolder: $HOME/var
        OverWrite: true

    - task: PowerShell@2
      displayName: ExtractFile
      inputs:
        targetType: 'inline'
        script: |
          tar -xvf $HOME/var/openshift-install-linux.tar.gz